import { Database } from './types_db'

export type Profile = Database['public']['Tables']['profiles']['Row']
export type Countries = Database['public']['Tables']['countries']['Row']
export type Positions = Database['public']['Tables']['positions']['Row']
export type Teams = Database['public']['Tables']['teams']['Row']
export type Exas = Database['public']['Tables']['exas']['Row']
export type Torneos = Database['public']['Tables']['torneos']['Row']
export type TorneoFase = Database['public']['Tables']['torneo_fase']['Row']
export type TiposPartido = Database['public']['Tables']['tipo_partido']['Row']
export type Fases = Database['public']['Tables']['fases']['Row']
export type Foot = Database['public']['Tables']['foot']['Row']
export type Players = Database['public']['Tables']['players']['Row']
export type Locations = Database['public']['Tables']['locations']['Row']
export type Fixtures = Database['public']['Tables']['fixtures']['Row']
export type FixturePlayers = Database['public']['Tables']['fixture_players']['Row']
export type FixtureTeams = Database['public']['Tables']['fixture_teams']['Row']
export type GetFixturesTeams = Database['public']['Functions']['get_fixture_teams_by_fixture_id']['Returns']
export type GetFixturesPlayers = Database['public']['Functions']['get_fixture_players_by_fixture_id']['Returns']

